export const stopwords = () => {
    return ["a","ada","adalah","adanya","adapun","agak","agaknya","agar","akan","akankah","akhir","akhiri","akhirnya","amat","amatlah","antar","antara","antaranya","apaan","apabila","apalagi","apatah","arti","artinya","asal","asalkan","atas","atau","ataukah","ataupun","awal","awalnya","b","bagai","bagaikan","bagaimanakah","bagaimanapun","bagainamakah","bagi","bagian","bahkan","bahwa","bahwasannya","bahwasanya","baik","baiklah","bakal","bakalan","balik","banyak","baru","bawah","beberapa","beginian","beginikah","beginilah","begitukah","begitulah","begitupun","bekerja","belakang","belakangan","belum","belumlah","benar","benarkah","benarlah","berada","berakhir","berakhirlah","berakhirnya","berapakah","berapalah","berapapun","berarti","berawal","berbagai","berdatangan","beri","berikan","berikut","berikutnya","berjumlah","berkali-kali","berkata","berkehendak","berkeinginan","berkenaan","berlainan","berlalu","berlangsung","berlebihan","bermacam","bermacam-macam","bermaksud","bermula","bersama","bersama-sama","bersiap","bersiap-siap","bertanya","bertanya-tanya","berturut","berturut-turut","bertutur","berujar","berupa","besar","betul","betulkah","biasa","biasanya","bila","bilakah","bisa","bisakah","boleh","bolehkah","bolehlah","buat","bulan","bung","c","cara","caranya","cukup","cukupkah","cukuplah","cuma","d","dahulu","dalam","dan","dapat","dari","daripada","datang","dekat","demi","demikian","demikianlah","dengan","depan","di","diakhiri","diakhirinya","diantara","diantaranya","diberi","diberikan","diberikannya","dibuat","dibuatnya","didapat","didatangkan","digunakan","diibaratkan","diibaratkannya","diingat","diingatkan","diinginkan","dijawab","dijelaskan","dijelaskannya","dikarenakan","dikatakan","dikatakannya","dikerjakan","diketahui","diketahuinya","dikira","dilakukan","dilalui","dilihat","dimaksud","dimaksudkan","dimaksudkannya","dimaksudnya","diminta","dimintai","dimisalkan","dimulai","dimulailah","dimulainya","dimungkinkan","dini","dipastikan","diperbuat","diperbuatnya","dipergunakan","diperkirakan","diperlihatkan","diperlukan","diperlukannya","dipersoalkan","dipertanyakan","dipunyai","diri","dirinya","disampaikan","disebut","disebutkan","disebutkannya","disini","disinilah","ditambahkan","ditandaskan","ditanya","ditanyai","ditanyakan","ditegaskan","ditujukan","ditunjuk","ditunjuki","ditunjukkan","ditunjukkannya","ditunjuknya","dituturkan","dituturkannya","diucapkan","diucapkannya","diungkapkan","dong","dua","dulu","e","empat","enak","enggak","enggaknya","entah","entahlah","f","g","guna","gunakan","h","hadap","hai","hal","halo","hallo","hampir","hanya","hanyalah","hari","harus","haruslah","harusnya","helo","hello","hendak","hendaklah","hendaknya","hingga","i","ialah","ibarat","ibaratkan","ibaratnya","ikut","ingat","ingat-ingat","inginkah","inginkan","inikah","inilah","itukah","itulah","j","jadi","jadilah","jadinya","jangan","jangankan","janganlah","jauh","jawab","jawaban","jawabnya","jelas","jelaskan","jelaslah","jelasnya","jika","jikalau","juga","jumlah","jumlahnya","justru","k","kadar","kala","kalau","kalaulah","kalaupun","kali","kan","kapankah","kapanpun","karena","karenanya","kasus","kata","katakan","katakanlah","katanya","ke","keadaan","kebetulan","kecil","kedua","keduanya","keinginan","kelamaan","kelihatan","kelihatannya","kelima","keluar","kembali","kemudian","kemungkinan","kemungkinannya","kena","kepada","kepadanya","kerja","kesampaian","keseluruhan","keseluruhannya","keterlaluan","ketika","khusus","khususnya","kini","kinilah","kira","kira-kira","kiranya","kok","kurang","l","lagi","lagian","lah","lain","lainnya","laku","lalu","lama","lamanya","langsung","lanjut","lanjutnya","lebih","lewat","lihat","lima","luar","m","macam","maka","makanya","makin","maksud","malah","malahan","mampu","mampukah","mana","manakala","manalagi","masa","masalah","masalahnya","masih","masihkah","masing","masing-masing","masuk","mata","mau","maupun","melainkan","melakukan","melalui","melihat","melihatnya","memang","memastikan","memberi","memberikan","membuat","memerlukan","memihak","meminta","memintakan","memisalkan","memperbuat","mempergunakan","memperkirakan","memperlihatkan","mempersiapkan","mempersoalkan","mempertanyakan","mempunyai","memulai","memungkinkan","menaiki","menambahkan","menandaskan","menanti","menanti-nanti","menantikan","menanya","menanyai","menanyakan","mendapat","mendapatkan","mendatang","mendatangi","mendatangkan","menegaskan","mengakhiri","mengatakan","mengatakannya","mengenai","mengerjakan","mengetahui","menggunakan","menghendaki","mengibaratkan","mengibaratkannya","mengingat","mengingatkan","menginginkan","mengira","mengucapkan","mengucapkannya","mengungkapkan","menjadi","menjawab","menjelaskan","menuju","menunjuk","menunjuki","menunjukkan","menunjuknya","menurut","menuturkan","menyampaikan","menyangkut","menyatakan","menyebutkan","menyeluruh","menyiapkan","merasa","merupakan","meski","meskipun","meyakini","meyakinkan","minta","mirip","misal","misalkan","misalnya","mohon","mula","mulai","mulailah","mulanya","mungkin","mungkinkah","n","nah","naik","namun","nanti","nantinya","nya","nyaris","nyata","nyatanya","o","oleh","olehnya","p","pada","padahal","padanya","pak","paling","panjang","pantas","para","pasti","pastilah","penting","pentingnya","per","percuma","perlu","perlukah","perlunya","pernah","persoalan","pertama","pertama-tama","pertanyaan","pertanyakan","pihak","pihaknya","pukul","pula","pun","punya","q","r","rasa","rasanya","rupa","rupanya","s","saat","saatnya","saja","sajalah","salam","saling","sama","sama-sama","sambil","sampai","sampai-sampai","sampaikan","sana","sangat","sangatlah","sangkut","satu","saya","sayalah","se","sebab","sebabnya","sebagai","sebagaimana","sebagainya","sebagian","sebaik","sebaik-baiknya","sebaiknya","sebaliknya","sebanyak","sebegini","sebegitu","sebelum","sebelumnya","sebenarnya","seberapa","sebesar","sebetulnya","sebisanya","sebuah","sebut","sebutlah","sebutnya","secara","secukupnya","sedang","sedangkan","sedemikian","sedikit","sedikitnya","seenaknya","segala","segalanya","segera","seharusnya","sehingga","seingat","sejak","sejauh","sejenak","sejumlah","sekadar","sekadarnya","sekali","sekali-kali","sekalian","sekaligus","sekalipun","sekarang","sekaranglah","sekecil","seketika","sekiranya","sekitar","sekitarnya","sekurang-kurangnya","sekurangnya","sela","selain","selaku","selalu","selama","selama-lamanya","selamanya","selanjutnya","seluruh","seluruhnya","semacam","semakin","semampu","semampunya","semasa","semasih","semata","semata-mata","semaunya","sementara","semisal","semisalnya","sempat","semua","semuanya","semula","sendiri","sendirian","sendirinya","seolah","seolah-olah","seorang","sepanjang","sepantasnya","sepantasnyalah","seperlunya","seperti","sepertinya","sepihak","sering","seringnya","serta","serupa","sesaat","sesama","sesampai","sesegera","sesekali","seseorang","sesuatu","sesuatunya","sesudah","sesudahnya","setelah","setempat","setengah","seterusnya","setiap","setiba","setibanya","setidak-tidaknya","setidaknya","setinggi","seusai","sewaktu","siap","siapakah","siapapun","sini","sinilah","soal","soalnya","suatu","sudah","sudahkah","sudahlah","supaya","t","tadi","tadinya","tahu","tak","tambah","tambahnya","tampak","tampaknya","tandas","tandasnya","tanpa","tanya","tanyakan","tanyanya","tapi","tegas","tegasnya","telah","tempat","tentang","tentu","tentulah","tentunya","tepat","terakhir","terasa","terbanyak","terdahulu","terdapat","terdiri","terhadap","terhadapnya","teringat","teringat-ingat","terjadi","terjadilah","terjadinya","terkira","terlalu","terlebih","terlihat","termasuk","ternyata","tersampaikan","tersebut","tersebutlah","tertentu","tertuju","terus","terutama","tetap","tetapi","tiap","tiba","tiba-tiba","tidakkah","tidaklah","tiga","toh","tuju","tunjuk","turut","tutur","tuturnya","u","ucap","ucapnya","ujar","ujarnya","umumnya","ungkap","ungkapnya","untuk","usah","usai","v","w","waduh","wah","wahai","waktunya","walau","walaupun","wong","x","y","yaitu","yakin","yakni","yang","z"];
}

export const slangwords = () => {
    return ['km', 'yah', 'udah', 'kan', 'kok', 'cowok', 'cewek', 'bkn', 'lu',
    'pake', 'engga', 'gimana', 'dah', 'gak', 'bgt', 'banget', 'indo',
    'msh', 'yg', 'dgn', 'gue', 'gw', 'aja', 'ajah', 'bener', 'klo',
    'kalo', 'nggak', 'ga', 'tuh', 'gitu', 'gini', 'kelakuan', 'pak',
    'bu', 'nih', 'cwe', 'cwo', 'ente', 'tp', 'kyk', 'jg', 'krn',
    'bikin', 'emang', 'skrg', 'ngk', 'tuk', 'tdk', 'duit', 'pdhl',
    'sdh', 'ngapain', 'mba', 'kak', 'ka', 'mbak', 'blm', 'lg',
    'ngerti', 'dapet', 'pantes', 'gpp', 'doang', 'ngaku', 'kayak',
    'loe', 'org', 'prof', 'dok', 'bacod', 'bacot', 'mrk', 'milih',
    'asu', 'radikul', 'bet', 'noh', 'nuduh', 'jgn', 'uu', 'dll',
    'gaes', 'guys', 'info', 'lonte', 'elu', 'elo', 'tau', 'dlu',
    'liat', 'trs', 'trus', 'klu', 'jd', 'adlh', 'bro', 'spt', 'thn',
    'dg', 'kadrun', 'sewot', 'belom', 'art', 'irt', 'napi', 'anying',
    'ko', 'om', 'pengen', 'makasih', 'dik', 'pantesan', 'abang', 'cm',
    'gondrong', 'kek', 'pungli', 'curhat', 'pns', 'mampus', 'gmn',
    'bocil', 'dikit', 'dr', 'doyan', 'dpr', 'dlm', 'gapapa', 'ngerasa',
    'mcm', 'mkn', 'fix', 'moga', 'gada', 'sm', 'sosmed', 'ortu',
    'nemu', 'pedes', 'dilakuin', 'peduli', 'pede', 'ngerasain',
    'gelut', 'nanges', 'nunjukin', 'maafin', 'ngabisin', 'sono',
    'gausah', 'belain', 'bestie', 'prank', 'ngakak', 'emg', 'gatau',
    'kelar', 'pinter', 'gajadi', 'ngibulin', 'tiati', 'diplagiat',
    'rame', 'sebel', 'ama', 'kaga', 'author', 'excuses', 'sick',
    'fandom', 'gws', 'ngatain', 'ngaca', 'lo', 'napa', 'kemaren',
    'diem', 'kasian', 'pala', 'bgtu', 'bs', 'ditutupin', 'akuin',
    'boti', 'bnyk', 'bct', 'males', 'copas', 'bpk', 'lagian', 'legowo',
    'utk', 'sampeyan', 'kdpn', 'cuan', 'parte', 'dpt', 'brpa',
    'dibiarin', 'koq', 'bini', 'no', 'kaleee', 'malming', 'anggep',
    'dateng', 'pulkam', 'bales', 'sblm', 'ntar', 'entar', 'maknye',
    'umi', 'tetep', 'yach', 'jelasin', 'mls', 'ngajar', 'ampe',
    'otewe', 'the real', 'mikirin', 'mnyt', 'kmrn', 'senpi', 'segepok',
    'digaplok', 'mingkem', 'kl', 'ttg', 'parti', 'yup', 'td', 'abis',
    'rada', 'make', 'lbh', 'klpn', 'emng', 'nempel', 'sll', 'bp', 'u',
    'aj', 'gk', 'hrs', 'ngejudge', 'karna', 'gua', 'amat', 'dmn',
    'ttp', 'real', 'serem', 'acakadut', 'nyokap', 'bokap', 'btw',
    'lgi', 'tmpt', 'emak', 'ngentot', 'dikatain', 'pgn', 'dri',
    'drpada', 'drpd', 'gth', 'kdng', 'kah', 'orderan', 'enteng',
    'kepoin', 'ngga', 'spek', 'nongol', 'ato', 'gaada', 'anj', 'ndak',
    'nyari', 'odgj', 'pansos', 'kudet', 'sapa', 'samsek', 'war',
    'situ', 'dongok', 'dongo', 'anget', 'utang', 'budek', 'ngamuk',
    'bego', 'begok', 'nyindir', 'gatel', 'nyinyir', 'usah', 'caper',
    'kang', 'bnr', 'byk', 'tlh', 'kpd', 'kagak', 'cepet', 'kelen',
    'mo', 'tar', 'mabok', 'belagu', 'mlh', 'mayan', 'sy', 'ultah',
    'bosen', 'budget', 'baper', 'respect', 'macem', 'mulu', 'cpt',
    'plis', 'pls', 'sklh', 'loyal', 'luv', 'babeh', 'gapernah', 'ukt',
    'sgt', 'sprt', 'cakep', 'ujan', 'sbb', 'melulu', 'kk', 'sorry',
    'ketemu', 'pd', 'chat', 'vibes', 'demen', 'gampang', 'pen', 'y',
    'doi', 'insecure', 'capek', 'cape', 'support', 'dek', 'dede', 'ak',
    'stay', 'gais', 'member', 'non', 'pasutri', 'bg', 'milad', 'mamah',
    'papah', 'mama', 'ayah', 'syg', 'prnh', 'deket', 'teh', 'image',
    'tsb', 'effort', 'spy', 'tweet', 'twit', 'gede', 'modus', 'mikir',
    'review', 'glowing', 'tumben', 'thread', 'ges', 'cwek', 'cwok',
    'knp', 'rules', 'nnti', 'leader', 'kpn', 'statement', 'dimarahin',
    'ditanyain', 'dimiripin', 'dirajin', 'ditemuin', 'dibanyakin',
    'dibikin', 'diajarin', 'digituin', 'ditambahin', 'diomongin',
    'dibilangin', 'dilihatin', 'dikeluarin', 'dibayangin', 'dibela2in',
    'dibayarin', 'dibiayain', 'dipaksain', 'dibiasain', 'ngebiasain',
    'ngerjain', 'ngrasain', 'ngurusin', 'ngomongin', 'ngemis', 'ngaco',
    'ngawur', 'ngomong', 'ngobrol', 'ngambek', 'ngidam', 'ngopi',
    'ngeliat', 'ngeluh', 'ngakunya', 'ngedesah', 'ngotot', 'ngurusi',
    'ngutang', 'ngelak', 'ngelacur', 'ngelunjak', 'ngegembel',
    'ngelukis', 'ngerinya', 'ngeri', 'ngotak', 'ngambil', 'ngembat',
    'ngapa', 'ngewe', 'ngeres', 'ngebacot', 'ngerusak', 'ngasih',
    'ngejual', 'ngebet', 'ngibul', 'ngepil', 'ngetik', 'kira2', 'lagi2', 'ibu2', 'bapak2', 'marah2', 'orang2', 'teriak2', 'org2', 'baik2', 'mas2', 'bener2', 'hal2', 'anak2', 'tahu2', 'jangan2', 'calon2', 'sama2', 'jelas2', 'pasar2', 'pilih2', 'ujung2', 'ubur2', 'diam2', 'agak2', 'rata2', 'ustad2', 'engga2', 'abal2', 'kadang2', 'lama2', 'kalimat2', 'muluk2', 'reka2', 'cwok2', 'pegang2', 'sok2', 'manusia2', 'oke2', 'pura2', 'jarang2', 'dikit2', 'amrik', 'film2', 'tagih2']
}

export const formalwords = () => {
    return ['kamu', 'ya', 'sudah', 'bukan', 'kenapa', 'laki laki', 'perempuan',
    'bukan', 'kamu', 'pakai', 'tidak', 'bagaimana', 'sudah', 'tidak',
    'sekali', 'sekali', 'indonesia', 'masih', 'yang', 'dengan', 'aku',
    'aku', 'saja', 'saja', 'benar', 'kalau', 'kalau', 'tidak', 'tidak',
    'itu', 'begitu', 'begini', 'perlakuan', 'bapak', 'ibu', 'ini',
    'perempuan', 'laki laki', 'kamu', 'tapi', 'seperti', 'juga',
    'karena', 'buat', 'memang', 'sekarang', 'tidak', 'untuk', 'tidak',
    'uang', 'padahal', 'sudah', 'kenapa', 'kakak', 'kakak', 'kakak',
    'kakak', 'belum', 'lagi', 'mengerti', 'dapat', 'pantas',
    'tidak apa apa', 'saja', 'mengaku', 'seperti', 'kamu', 'orang',
    'professor', 'dokter', 'ucapan', 'ucapan', 'mereka', 'pilih',
    'anjing', 'radikal', 'sekali', 'itu', 'tuduh', 'jangan',
    'undang undang', 'dan lain lain', 'teman teman', 'teman teman',
    'informasi', 'pelacur', 'kamu', 'kamu', 'tahu', 'dulu', 'lihat',
    'terus', 'terus', 'kalau', 'jadi', 'adalah', 'saudara', 'seperti',
    'tahun', 'dengan', 'kadal gurun', 'sinis', 'belum',
    'asisten rumah tangga', 'ibu rumah tangga', 'narapidana', 'anjing',
    'kenapa', 'paman', 'ingin', 'terima kasih', 'adik', 'pantas',
    'kakak', 'centimeter', 'panjang', 'saja', 'pungutan liar',
    'curahan hati', 'pegawai negeri sipil', 'mati', 'bagaimana',
    'bocah kecil', 'sedikit', 'dari', 'suka',
    'dewan perwakilan rakyat', 'dalam', 'tidak apa apa', 'merasa',
    'macam', 'makan', 'pasti', 'semoga', 'tidak ada', 'sama',
    'sosial media', 'orang tua', 'Menemukan', 'pedas', 'dilakukan',
    'perduli', 'percaya diri', 'merasakan', 'berkelahi', 'Menangis',
    'menunjukan', 'maafkan', 'menghabiskan', 'kesana', 'tidak perlu',
    'membela', 'sahabat', 'tertipu', 'lucu', 'memang', 'tidak tahu',
    'selesai', 'pintar', 'tidak jadi', 'membohongi', 'hati-hati',
    'ditiru', 'ramai', 'sebal', 'sama', 'tidak', 'penulis', 'alasan',
    'sakit', 'penggemar', 'cepat sembuh', 'menghina', 'berkaca',
    'kamu', 'kenapa', 'kemarin', 'diam', 'kasihan', 'kepala', 'begitu',
    'bisa', 'ditutupi', 'mengakui', 'bonceng tiga', 'banyak', 'bacot',
    'malas', 'tiru', 'bapak', 'padahal', 'mempersilahkan', 'untuk',
    'kamu', 'kedepan', 'uang', 'partai', 'dapat', 'berapa',
    'dibiarkan', 'kenapa', 'istri', 'tidak', 'kali', 'malam mingguan',
    'anggap', 'datang', 'pulang kampung', 'balas', 'sebelum', 'nanti',
    'nanti', 'ibunya', 'ibu', 'tetap', 'yah', 'jelaskan', 'malas',
    'mengajar', 'sampai', 'dalam perjalanan', 'asli', 'memikirkan',
    'monyet', 'kemarin', 'senjata api', 'setumpuk', 'tampar', 'diam',
    'kalau', 'tentang', 'kelompok', 'ya', 'tadi', 'habis', 'agak',
    'pakai', 'lebih', 'kalaupun', 'memang', 'menempel', 'selalu',
    'bapak', 'kamu', 'saja', 'tidak', 'harus', 'menghakimi', 'karena',
    'aku', 'banget', 'dimana', 'tetap', 'nyata', 'seram', 'kacau',
    'ibu', 'bapak', 'ngomong ngomong', 'lagi', 'tempat', 'ibu',
    'bersetubuh', 'diejek', 'ingin', 'dari', 'daripada', 'daripada',
    'begitu', 'kadang', 'bukan', 'pesanan', 'mudah', 'cari tahu',
    'tidak', 'spesifikasi', 'muncul', 'atau', 'tidak ada', 'anjing',
    'tidak', 'cari', 'orang dengan gangguan jiwa', 'panjat sosial',
    'kurang tahu', 'siapa', 'sama sekali', 'perang', 'kamu', 'bodoh',
    'bodoh', 'hangat', 'hutang', 'tuli', 'mengamuk', 'bodoh', 'bodoh',
    'sindir', 'gatal', 'cerewet', 'perlu', 'cari perhatian', 'tukang',
    'benar', 'banyak', 'telah', 'kepada', 'tidak', 'cepat', 'kalian',
    'mau', 'nanti', 'mabuk', 'sombong', 'malah', 'lumayan', 'saya',
    'ulang tahun', 'bosan', 'biaya', 'bawa perasaan', 'hormat',
    'macam', 'terus', 'cepat', 'tolong', 'tolong', 'sekolah', 'setia',
    'cinta', 'bapak', 'tidak pernah', 'uang kuliah tunggal', 'sangat',
    'seperti', 'bagus', 'hujan', 'sebab', 'terus', 'kakak', 'maaf',
    'bertemu', 'pada', 'pesan', 'aura', 'suka', 'mudah', 'ingin', 'ya',
    'dia', 'Tidak percaya diri', 'lelah', 'lelah', 'dukung', 'adek',
    'adek', 'aku', 'tetap', 'teman teman', 'anggota', 'tidak',
    'pasangan suami istri', 'bagi', 'ulang tahun', 'ibu', 'bapak',
    'ibu', 'bapak', 'sayang', 'pernah', 'dekat', 'kakak perempuan',
    'citra', 'tersebut', 'usaha', 'supaya', 'cuitan', 'cuitan',
    'besar', 'modal dusta', 'berpikir', 'ulasan', 'cerah',
    'tidak biasa', 'cerita', 'teman teman', 'perempuan', 'laki laki',
    'kenapa', 'aturan', 'nanti', 'pemimpin', 'kapan', 'pendapat',
    'marah', 'tanya', 'mirip', 'rajin', 'temu', 'banyak', 'dibuat',
    'ajar', 'diperlakukan', 'tambah', 'omong', 'bilang', 'lihat',
    'keluar', 'dibayangi', 'bela', 'bayar', 'biayai', 'paksa',
    'dibiasakan', 'biasa', 'mengerjakan', 'rasa', 'urus', 'omong',
    'mengemis', 'berucap sembarangan', 'asal asalan', 'bicara',
    'bicara', 'marah', 'mengidam', 'minum kopi', 'melihat', 'mengeluh',
    'mengaku', 'mendesah', 'kekeh', 'mengurusi', 'berhutang',
    'mengelak', 'melacur', 'melunjak', 'gembel', 'melukis',
    'mengerikan', 'mengerikan', 'berpikir', 'mengambil', 'mengambil',
    'kenapa', 'bersetubuh', 'berpikir mesum', 'berbicara', 'rusak',
    'memberi', 'menjual', 'ingin', 'membohongi', 'membocorkan',
    'mengetik', 'kira-kira', 'lagi-lagi', 'ibu-ibu', 'bapak-bapak', 'marah-marah', 'orang-orang', 'berteriak', 'orang-orang', 'baik-baik', 'kakak-kakak', 'benar-benar', 'hal-hal', 'anak-anak', 'tahu-tahu', 'jangan-jangan', 'calon-calon', 'sama-sama', 'jelas-jelas', 'pasar-pasar', 'pilih-pilih', 'ujung-ujung', 'ubur-ubur', 'diam-diam', 'agak-agak', 'rata-rata', 'ustad-ustad', 'tidak-tidak', 'abal-abal', 'kadang-kadang', 'lama-lama', 'kalimat-kalimat', 'muluk-muluk', 'reka-reka', 'laki-laki', 'pegang-pegang', 'berlagak', 'manusia-manusia', 'oke-oke', 'berpura-pura', 'jarang-jarang', 'sedikit-sedikit', 'amerika', 'film-film', 'tagih-tagih']
}