class SlangWord:
    
    informalWord = ['km', 'yah', 'udah', 'kan', 'kok', 'cowok', 'cewek', 'bkn', 'lu',
       'pake', 'engga', 'gimana', 'dah', 'gak', 'bgt', 'banget', 'indo',
       'msh', 'yg', 'dgn', 'gue', 'gw', 'aja', 'ajah', 'bener', 'klo',
       'kalo', 'nggak', 'ga', 'tuh', 'gitu', 'gini', 'kelakuan', 'pak',
       'bu', 'nih', 'cwe', 'cwo', 'ente', 'tp', 'kyk', 'jg', 'krn',
       'bikin', 'emang', 'skrg', 'ngk', 'tuk', 'tdk', 'duit', 'pdhl',
       'sdh', 'ngapain', 'mba', 'kak', 'ka', 'mbak', 'blm', 'lg',
       'ngerti', 'dapet', 'pantes', 'gpp', 'doang', 'ngaku', 'kayak',
       'loe', 'org', 'prof', 'dok', 'bacod', 'bacot', 'mrk', 'milih',
       'asu', 'radikul', 'bet', 'noh', 'nuduh', 'jgn', 'uu', 'dll',
       'gaes', 'guys', 'info', 'lonte', 'elu', 'elo', 'tau', 'dlu',
       'liat', 'trs', 'trus', 'klu', 'jd', 'adlh', 'bro', 'spt', 'thn',
       'dg', 'kadrun', 'sewot', 'belom', 'art', 'irt', 'napi', 'anying',
       'ko', 'om', 'pengen', 'makasih', 'dik', 'pantesan', 'abang', 'cm',
       'gondrong', 'kek', 'pungli', 'curhat', 'pns', 'mampus', 'gmn',
       'bocil', 'dikit', 'dr', 'doyan', 'dpr', 'dlm', 'gapapa', 'ngerasa',
       'mcm', 'mkn', 'fix', 'moga', 'gada', 'sm', 'sosmed', 'ortu',
       'nemu', 'pedes', 'dilakuin', 'peduli', 'pede', 'ngerasain',
       'gelut', 'nanges', 'nunjukin', 'maafin', 'ngabisin', 'sono',
       'gausah', 'belain', 'bestie', 'prank', 'ngakak', 'emg', 'gatau',
       'kelar', 'pinter', 'gajadi', 'ngibulin', 'tiati', 'diplagiat',
       'rame', 'sebel', 'ama', 'kaga', 'author', 'excuses', 'sick',
       'fandom', 'gws', 'ngatain', 'ngaca', 'lo', 'napa', 'kemaren',
       'diem', 'kasian', 'pala', 'bgtu', 'bs', 'ditutupin', 'akuin',
       'boti', 'bnyk', 'bct', 'males', 'copas', 'bpk', 'lagian', 'legowo',
       'utk', 'sampeyan', 'kdpn', 'cuan', 'parte', 'dpt', 'brpa',
       'dibiarin', 'koq', 'bini', 'no', 'kaleee', 'malming', 'anggep',
       'dateng', 'pulkam', 'bales', 'sblm', 'ntar', 'entar', 'maknye',
       'umi', 'tetep', 'yach', 'jelasin', 'mls', 'ngajar', 'ampe',
       'otewe', 'the real', 'mikirin', 'mnyt', 'kmrn', 'senpi', 'segepok',
       'digaplok', 'mingkem', 'kl', 'ttg', 'parti', 'yup', 'td', 'abis',
       'rada', 'make', 'lbh', 'klpn', 'emng', 'nempel', 'sll', 'bp', 'u',
       'aj', 'gk', 'hrs', 'ngejudge', 'karna', 'gua', 'amat', 'dmn',
       'ttp', 'real', 'serem', 'acakadut', 'nyokap', 'bokap', 'btw',
       'lgi', 'tmpt', 'emak', 'ngentot', 'dikatain', 'pgn', 'dri',
       'drpada', 'drpd', 'gth', 'kdng', 'kah', 'orderan', 'enteng',
       'kepoin', 'ngga', 'spek', 'nongol', 'ato', 'gaada', 'anj', 'ndak',
       'nyari', 'odgj', 'pansos', 'kudet', 'sapa', 'samsek', 'war',
       'situ', 'dongok', 'dongo', 'anget', 'utang', 'budek', 'ngamuk',
       'bego', 'begok', 'nyindir', 'gatel', 'nyinyir', 'usah', 'caper',
       'kang', 'bnr', 'byk', 'tlh', 'kpd', 'kagak', 'cepet', 'kelen',
       'mo', 'tar', 'mabok', 'belagu', 'mlh', 'mayan', 'sy', 'ultah',
       'bosen', 'budget', 'baper', 'respect', 'macem', 'mulu', 'cpt',
       'plis', 'pls', 'sklh', 'loyal', 'luv', 'babeh', 'gapernah', 'ukt',
       'sgt', 'sprt', 'cakep', 'ujan', 'sbb', 'melulu', 'kk', 'sorry',
       'ketemu', 'pd', 'chat', 'vibes', 'demen', 'gampang', 'pen', 'y',
       'doi', 'insecure', 'capek', 'cape', 'support', 'dek', 'dede', 'ak',
       'stay', 'gais', 'member', 'non', 'pasutri', 'bg', 'milad', 'mamah',
       'papah', 'mama', 'ayah', 'syg', 'prnh', 'deket', 'teh', 'image',
       'tsb', 'effort', 'spy', 'tweet', 'twit', 'gede', 'modus', 'mikir',
       'review', 'glowing', 'tumben', 'thread', 'ges', 'cwek', 'cwok',
       'knp', 'rules', 'nnti', 'leader', 'kpn', 'statement', 'dimarahin',
       'ditanyain', 'dimiripin', 'dirajin', 'ditemuin', 'dibanyakin',
       'dibikin', 'diajarin', 'digituin', 'ditambahin', 'diomongin',
       'dibilangin', 'dilihatin', 'dikeluarin', 'dibayangin', 'dibela2in',
       'dibayarin', 'dibiayain', 'dipaksain', 'dibiasain', 'ngebiasain',
       'ngerjain', 'ngrasain', 'ngurusin', 'ngomongin', 'ngemis', 'ngaco',
       'ngawur', 'ngomong', 'ngobrol', 'ngambek', 'ngidam', 'ngopi',
       'ngeliat', 'ngeluh', 'ngakunya', 'ngedesah', 'ngotot', 'ngurusi',
       'ngutang', 'ngelak', 'ngelacur', 'ngelunjak', 'ngegembel',
       'ngelukis', 'ngerinya', 'ngeri', 'ngotak', 'ngambil', 'ngembat',
       'ngapa', 'ngewe', 'ngeres', 'ngebacot', 'ngerusak', 'ngasih',
       'ngejual', 'ngebet', 'ngibul', 'ngepil', 'ngetik']
    
    formalWord = ['kamu', 'ya', 'sudah', 'bukan', 'kenapa', 'laki laki', 'perempuan',
       'bukan', 'kamu', 'pakai', 'tidak', 'bagaimana', 'sudah', 'tidak',
       'sekali', 'sekali', 'indonesia', 'masih', 'yang', 'dengan', 'aku',
       'aku', 'saja', 'saja', 'benar', 'kalau', 'kalau', 'tidak', 'tidak',
       'itu', 'begitu', 'begini', 'perlakuan', 'bapak', 'ibu', 'ini',
       'perempuan', 'laki laki', 'kamu', 'tapi', 'seperti', 'juga',
       'karena', 'buat', 'memang', 'sekarang', 'tidak', 'untuk', 'tidak',
       'uang', 'padahal', 'sudah', 'kenapa', 'kakak', 'kakak', 'kakak',
       'kakak', 'belum', 'lagi', 'mengerti', 'dapat', 'pantas',
       'tidak apa apa', 'saja', 'mengaku', 'seperti', 'kamu', 'orang',
       'professor', 'dokter', 'ucapan', 'ucapan', 'mereka', 'pilih',
       'anjing', 'radikal', 'sekali', 'itu', 'tuduh', 'jangan',
       'undang undang', 'dan lain lain', 'teman teman', 'teman teman',
       'informasi', 'pelacur', 'kamu', 'kamu', 'tahu', 'dulu', 'lihat',
       'terus', 'terus', 'kalau', 'jadi', 'adalah', 'saudara', 'seperti',
       'tahun', 'dengan', 'kadal gurun', 'sinis', 'belum',
       'asisten rumah tangga', 'ibu rumah tangga', 'narapidana', 'anjing',
       'kenapa', 'paman', 'ingin', 'terima kasih', 'adik', 'pantas',
       'kakak', 'centimeter', 'panjang', 'saja', 'pungutan liar',
       'curahan hati', 'pegawai negeri sipil', 'mati', 'bagaimana',
       'bocah kecil', 'sedikit', 'dari', 'suka',
       'dewan perwakilan rakyat', 'dalam', 'tidak apa apa', 'merasa',
       'macam', 'makan', 'pasti', 'semoga', 'tidak ada', 'sama',
       'sosial media', 'orang tua', 'Menemukan', 'pedas', 'dilakukan',
       'perduli', 'percaya diri', 'merasakan', 'berkelahi', 'Menangis',
       'menunjukan', 'maafkan', 'menghabiskan', 'kesana', 'tidak perlu',
       'membela', 'sahabat', 'tertipu', 'lucu', 'memang', 'tidak tahu',
       'selesai', 'pintar', 'tidak jadi', 'membohongi', 'hati-hati',
       'ditiru', 'ramai', 'sebal', 'sama', 'tidak', 'penulis', 'alasan',
       'sakit', 'penggemar', 'cepat sembuh', 'menghina', 'berkaca',
       'kamu', 'kenapa', 'kemarin', 'diam', 'kasihan', 'kepala', 'begitu',
       'bisa', 'ditutupi', 'mengakui', 'bonceng tiga', 'banyak', 'bacot',
       'malas', 'tiru', 'bapak', 'padahal', 'mempersilahkan', 'untuk',
       'kamu', 'kedepan', 'uang', 'partai', 'dapat', 'berapa',
       'dibiarkan', 'kenapa', 'istri', 'tidak', 'kali', 'malam mingguan',
       'anggap', 'datang', 'pulang kampung', 'balas', 'sebelum', 'nanti',
       'nanti', 'ibunya', 'ibu', 'tetap', 'yah', 'jelaskan', 'malas',
       'mengajar', 'sampai', 'dalam perjalanan', 'asli', 'memikirkan',
       'monyet', 'kemarin', 'senjata api', 'setumpuk', 'tampar', 'diam',
       'kalau', 'tentang', 'kelompok', 'ya', 'tadi', 'habis', 'agak',
       'pakai', 'lebih', 'kalaupun', 'memang', 'menempel', 'selalu',
       'bapak', 'kamu', 'saja', 'tidak', 'harus', 'menghakimi', 'karena',
       'aku', 'banget', 'dimana', 'tetap', 'nyata', 'seram', 'kacau',
       'ibu', 'bapak', 'ngomong ngomong', 'lagi', 'tempat', 'ibu',
       'bersetubuh', 'diejek', 'ingin', 'dari', 'daripada', 'daripada',
       'begitu', 'kadang', 'bukan', 'pesanan', 'mudah', 'cari tahu',
       'tidak', 'spesifikasi', 'muncul', 'atau', 'tidak ada', 'anjing',
       'tidak', 'cari', 'orang dengan gangguan jiwa', 'panjat sosial',
       'kurang tahu', 'siapa', 'sama sekali', 'perang', 'kamu', 'bodoh',
       'bodoh', 'hangat', 'hutang', 'tuli', 'mengamuk', 'bodoh', 'bodoh',
       'sindir', 'gatal', 'cerewet', 'perlu', 'cari perhatian', 'tukang',
       'benar', 'banyak', 'telah', 'kepada', 'tidak', 'cepat', 'kalian',
       'mau', 'nanti', 'mabuk', 'sombong', 'malah', 'lumayan', 'saya',
       'ulang tahun', 'bosan', 'biaya', 'bawa perasaan', 'hormat',
       'macam', 'terus', 'cepat', 'tolong', 'tolong', 'sekolah', 'setia',
       'cinta', 'bapak', 'tidak pernah', 'uang kuliah tunggal', 'sangat',
       'seperti', 'bagus', 'hujan', 'sebab', 'terus', 'kakak', 'maaf',
       'bertemu', 'pada', 'pesan', 'aura', 'suka', 'mudah', 'ingin', 'ya',
       'dia', 'Tidak percaya diri', 'lelah', 'lelah', 'dukung', 'adek',
       'adek', 'aku', 'tetap', 'teman teman', 'anggota', 'tidak',
       'pasangan suami istri', 'bagi', 'ulang tahun', 'ibu', 'bapak',
       'ibu', 'bapak', 'sayang', 'pernah', 'dekat', 'kakak perempuan',
       'citra', 'tersebut', 'usaha', 'supaya', 'cuitan', 'cuitan',
       'besar', 'modal dusta', 'berpikir', 'ulasan', 'cerah',
       'tidak biasa', 'cerita', 'teman teman', 'perempuan', 'laki laki',
       'kenapa', 'aturan', 'nanti', 'pemimpin', 'kapan', 'pendapat',
       'marah', 'tanya', 'mirip', 'rajin', 'temu', 'banyak', 'dibuat',
       'ajar', 'diperlakukan', 'tambah', 'omong', 'bilang', 'lihat',
       'keluar', 'dibayangi', 'bela', 'bayar', 'biayai', 'paksa',
       'dibiasakan', 'biasa', 'mengerjakan', 'rasa', 'urus', 'omong',
       'mengemis', 'berucap sembarangan', 'asal asalan', 'bicara',
       'bicara', 'marah', 'mengidam', 'minum kopi', 'melihat', 'mengeluh',
       'mengaku', 'mendesah', 'kekeh', 'mengurusi', 'berhutang',
       'mengelak', 'melacur', 'melunjak', 'gembel', 'melukis',
       'mengerikan', 'mengerikan', 'berpikir', 'mengambil', 'mengambil',
       'kenapa', 'bersetubuh', 'berpikir mesum', 'berbicara', 'rusak',
       'memberi', 'menjual', 'ingin', 'membohongi', 'membocorkan',
       'mengetik']